---
- name: Install Remote Facts
  hosts: webserver
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: sami.fact
  tasks:
    - name: Create the remote directory
      file:
        state: directory
        recurse: yes
        path: "{{ remote_dir }}"
    - name: Install the new facts
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"
...