---
- name: shutdown web groups virtual machines
  hosts: web
  gather_facts: no
  tasks:
    - name: Unconditionally shut down the machine with all defaults
      community.general.shutdown:
        delay: 0

- name: shutdown database groups virtual machines
  hosts: database
  gather_facts: no
  tasks:
    - name: Unconditionally shut down the machine with all defaults
      community.general.shutdown:
        delay: 0
